<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MinecraftInstanceMigration.Application/MinecraftInstanceMigration.Application.csproj" />
    <ProjectReference Include="../MinecraftInstanceMigration.Infrastructure/MinecraftInstanceMigration.Infrastructure.csproj" />
  </ItemGroup>
</Project>
