using System.Text;

namespace MinecraftInstanceMigration.App.Presentation;

public static class UiText
{
    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["About"] = "このアプリについて",
        ["Action"] = "予定の操作",
        ["Apply choices"] = "選択を確定",
        ["Backup"] = "バックアップ",
        ["Backup required"] = "バックアップが必要",
        ["Backup used"] = "バックアップを使用",
        ["Backup size"] = "バックアップ容量",
        ["Browse…"] = "フォルダーを選ぶ…",
        ["Cancel"] = "キャンセル",
        ["Candidate folder"] = "調べるフォルダー",
        ["Capacity preflight"] = "空き容量の確認",
        ["Check capacity"] = "③ 空き容量を確認",
        ["Clear"] = "決定を取り消す",
        ["Confirm guarded rollback"] = "復旧内容の確認",
        ["Confirm migration"] = "移行内容の最終確認",
        ["Conflict:"] = "既存項目の扱い:",
        ["Copy size"] = "コピー容量",
        ["Destination"] = "移行先",
        ["Destination free"] = "移行先の空き容量",
        ["Exclude"] = "対象から外す",
        ["Execute migration"] = "④ 移行を実行",
        ["Execution and verification"] = "実行と内容確認",
        ["Expected kind"] = "想定する種類",
        ["Generate Preview"] = "① 移行内容を調べる",
        ["Include"] = "対象にする",
        ["Inspect"] = "フォルダーを調べる",
        ["Inspector"] = "フォルダー調査（任意）",
        ["Kind matches"] = "種類の一致",
        ["Migration actions"] = "移行の内訳",
        ["Migration Preview"] = "移行する",
        ["Migration Preview and Execution"] = "インスタンスのデータを移行",
        ["Migration preview entries"] = "移行する項目",
        ["Migration Report"] = "⑤ 移行結果",
        ["Name"] = "項目名",
        ["Observed entries"] = "見つかった項目",
        ["Observed state"] = "現在の状態",
        ["Overall result"] = "移行結果",
        ["Plan detail"] = "操作の理由",
        ["Read-only Instance Inspector"] = "フォルダーの内容を調べる",
        ["Recovery"] = "復旧",
        ["Recovery required"] = "復旧が必要です",
        ["Replace write size"] = "置換する容量",
        ["Reset Recommended"] = "おすすめに戻す",
        ["Safety workspace"] = "バックアップ・記録の保存先",
        ["Safety workspace free"] = "保存先の空き容量",
        ["Select All"] = "すべて対象にする",
        ["Select None"] = "すべて対象から外す",
        ["Selected row:"] = "② 選んだ行:",
        ["Source"] = "移行元",
        ["Start Guarded Rollback"] = "確認した内容で復旧",
        ["Start guarded rollback"] = "復旧内容を確認する",
        ["Start guarded rollback?"] = "元の状態への復旧を開始しますか？",
        ["Start Migration"] = "この内容で移行を開始",
        ["Start migration?"] = "移行を開始しますか？",
        ["Status"] = "状況",
        ["Language"] = "言語",
        ["Theme"] = "表示",
        ["Use Windows setting"] = "Windowsに合わせる",
        ["Light"] = "ライト",
        ["Dark"] = "ダーク",
        ["Next step"] = "次にすること",
        ["Choose an instance candidate folder"] = "調べるゲーム用フォルダーを選択",
        ["Choose source instance candidate folder"] = "移行元の古いゲーム用フォルダーを選択",
        ["Choose destination instance candidate folder"] = "移行先の新しいゲーム用フォルダーを選択",
        ["Choose safety workspace for journal and backup"] = "両インスタンスの外側にある保存先を選択",
        ["Choose folders → Review items → Check space → Confirm migration → Read result"] = "フォルダー選択 → 移す項目を確認 → 空き容量確認 → 移行 → 結果確認",
        ["Choose the old and new game folders. Close Minecraft and the launcher before migration."] = "移行元に古いインスタンス、移行先に新しいインスタンスを選びます。移行前にMinecraftとランチャーを終了してください。",
        ["Use separate folders containing options.txt or config; do not choose the same folder or its parent/child."] = "options.txtやconfigが直下にあるゲーム用フォルダーを選びます。同じフォルダーや親子のフォルダーは指定できません。",
        ["Choose an existing separate folder outside both instances. Replacement backups and operation records are saved here."] = "両インスタンスの外側にある別のフォルダーを選びます。置換前のバックアップと操作記録が保存されます。",
        ["Installer: run setup.exe once, then open the app from Start. Portable: extract the entire ZIP and run MinecraftInstanceMigrationTool.exe."] = "インストール版: setup.exeで導入し、以後はスタートメニューから起動します。ZIP版: 全体を展開し、MinecraftInstanceMigrationTool.exeを起動します。",
        ["Recommended leaves saves and screenshots unselected. Resolve choices, apply them, and pass capacity preflight before execution. The safety workspace stores the durable journal and any required replacement backup. Execution still revalidates live state before writing."] = "おすすめ設定ではワールド（saves）とスクリーンショットは対象外です。移したい行を選んで対象に追加してください。移行先に同じ項目がある場合は、スキップするかバックアップ後に置換するかを決め、選択を確定します。",
        ["Preview inspects source and destination without writing. After choices are applied, execution requires a safety workspace and a separate confirmation before Backup or migration writes can begin."] = "まず移行元と移行先を調べ、移す内容を一覧で確認します。この調査ではファイルを変更しません。移行は保存先・空き容量・最終確認がそろってから開始します。",
        ["Observes the selected folder and 11 known direct children. No copying, content reads, or changes. Results do not confirm a Minecraft instance or migration compatibility."] = "選んだフォルダーに移行対象の11項目があるかを調べます。ファイルは変更しません。MODやMinecraftのバージョン互換性は判定しません。",
        ["Missing = absent. Inaccessible / Unavailable = unknown. A reparse point is recorded without following it; a reparse point in the root path stops inspection."] = "見つからない項目は「なし」、読み取れない項目は「不明」です。リンク先はたどりません。指定フォルダーのパスにリンクが含まれる場合は調査を停止します。",
        ["Use an absolute local drive path. Network and device paths are unsupported. Cancellation takes effect between metadata calls. Observations can become stale."] = "このPCのローカルフォルダーを選んでください。ネットワーク共有は使用できません。調査後にファイルが変わった場合は、もう一度調べ直してください。",
        ["Migration did not complete normally. Automatic retry and automatic rollback are disabled."] = "移行が正常に完了していません。移行元・移行先・保存先をそのまま保管してください。自動で再実行や復旧は行いません。",
        ["Read-only projection of existing migration, backup, execution, verification, and recovery evidence. This report does not authorize or change workflow operations."] = "移行と内容確認の結果です。「完了」以外の結果を成功として扱わず、表示された状況を確認してください。",
        ["Phase 4.4 keeps reports in memory only. No report file is written automatically, and reports contain no filesystem paths or raw exception messages."] = "結果はこの画面で確認できます。結果ファイルの自動保存や外部送信はありません。データの確認が終わるまでバックアップと操作記録を保管してください。",
        ["This operation will write to the destination. Review the source, destination, and planned changes before continuing."] = "移行先のファイルを変更します。移行元・移行先・保存先と、コピー・置換する項目数を確認してください。置換する項目は先にバックアップします。",
        ["This operation changes the destination. Each action proceeds only while current filesystem and backup evidence still satisfy the existing safety guards."] = "移行先を変更して復旧します。移行後に変更されたデータを勝手に削除・上書きすることはありません。現在の状態とバックアップを検証できる場合にだけ進みます。",
        ["Unofficial community tool. Not affiliated with Mojang Studios or Microsoft."] = "非公式のコミュニティツールです。Mojang Studios・Microsoftとの提携はありません。",
        ["Choose a local folder, then select Inspect."] = "調べるフォルダーを選び、「フォルダーを調べる」を押してください。",
        ["Ready to inspect. Previous observations cleared."] = "調査できます。以前の調査結果はクリアしました。",
        ["Observing root and known-entry metadata…"] = "フォルダーと対象項目を調べています…",
        ["Observation finished. No files were changed."] = "調査が完了しました。ファイルは変更していません。",
        ["Observation incomplete. Review the root and entry states; no files were changed."] = "すべてを調べられませんでした。一覧の状態を確認してください。ファイルは変更していません。",
        ["Inspection cancelled. No result retained."] = "調査をキャンセルしました。結果は保持していません。",
        ["Choose source and destination folders, then generate a dry-run preview."] = "移行元と移行先を選び、「① 移行内容を調べる」を押してください。",
        ["Inspecting source and destination metadata for dry run…"] = "移行元と移行先を調べています。ファイルは変更しません…",
        ["Dry-run preview cancelled. No result retained."] = "移行内容の調査をキャンセルしました。結果は保持していません。",
        ["Migration was not started. No files were changed."] = "移行を開始しませんでした。ファイルは変更していません。",
        ["Preparing and verifying the required backup…"] = "置換前のデータをバックアップし、内容を確認しています…",
        ["Preparing execution. No backup is required for this plan…"] = "移行を準備しています。この内容では既存データの置換はありません…",
        ["Executing migration and independently verifying written content…"] = "移行中です。コピー・置換後の内容も確認しています…",
        ["Checking logical sizes and available capacity…"] = "必要な容量と保存先の空き容量を確認しています…",
        ["Capacity check cancelled. Migration remains blocked."] = "空き容量の確認をキャンセルしました。移行は開始できません。",
        ["Capacity information is unavailable. Migration remains blocked."] = "空き容量を確認できません。保存先を確認して調べ直してください。移行は開始できません。",
        ["Capacity check passed. Backup and migration may be started after confirmation."] = "空き容量を確認できました。「④ 移行を実行」で最終確認へ進めます。",
        ["Insufficient space on the destination volume. Migration remains blocked."] = "移行先の空き容量が不足しています。容量を確保して確認し直してください。",
        ["Insufficient space on the safety workspace volume. Migration remains blocked."] = "バックアップ・記録の保存先の空き容量が不足しています。保存先を変更するか容量を確保してください。",
        ["Insufficient shared volume space for migration writes and backup. Migration remains blocked."] = "移行先とバックアップ保存先が同じドライブにあり、合計の空き容量が不足しています。",
        ["Capacity check is blocked by the current migration plan."] = "移す項目や既存項目の扱いを決めてから、空き容量を確認してください。",
        ["Capacity has not been checked for the current preview and workspace."] = "現在の選択内容と保存先では、まだ空き容量を確認していません。",
        ["Destination and Safety workspace share the same volume; write and backup requirements are combined."] = "移行先とバックアップ保存先は同じドライブです。必要な容量を合算しています。",
        ["Destination and Safety workspace are evaluated independently."] = "移行先とバックアップ保存先の容量をそれぞれ確認しています。",
        ["Volume relationship has not been checked."] = "保存先のドライブはまだ確認していません。",
        ["Choices applied. Dry-run preview is ready. No files were changed."] = "選択を確定しました。保存先を選び、空き容量を確認してください。ファイルは変更していません。",
        ["Dry-run preview ready. Select a row to edit migration choices. No files were changed."] = "移行内容を確認できます。行を選んで移す項目を変更できます。まだファイルは変更していません。",
        ["Dry-run preview needs conflict decisions. Select a conflict row, choose Skip or Replace, then apply choices. No files were changed."] = "移行先に同じ項目があります。その行を選び、スキップか置換を決めて選択を確定してください。まだファイルは変更していません。",
        ["Dry-run preview is blocked. Review the listed states; no files were changed."] = "この内容では移行できません。一覧の操作の理由を確認してください。ファイルは変更していません。",
        ["Selection or conflict choices changed. Apply choices to refresh the dry-run preview."] = "選択内容を変更しました。「選択を確定」を押して一覧を更新してください。",
        ["Ready to generate a new dry-run preview. Previous preview and choices cleared."] = "フォルダーを変更したので、移行内容を調べ直してください。以前の選択はクリアしました。",
        ["RecoveryRequired. Do not execute again; review recovery evidence before changing files."] = "復旧が必要です。再実行せず、フォルダーとバックアップを保管して復旧欄を確認してください。",
        ["Migration cancelled before execution completed. No further work was started."] = "移行の完了前にキャンセルしました。その後の処理は開始していません。結果を確認してください。",
        ["No recovery diagnosis is active."] = "復旧が必要な結果はありません。",
        ["Rollback is blocked because recovery evidence is incomplete."] = "復旧に必要な記録を確認できないため、復旧を開始できません。",
        ["Rollback confirmation could not be displayed. No rollback changes were made."] = "復旧の確認画面を開けませんでした。復旧による変更はありません。",
        ["Rollback was not started. No rollback changes were made."] = "復旧を開始しませんでした。復旧による変更はありません。",
        ["Guarded rollback is running. Current evidence is revalidated before each change."] = "復旧しています。各変更の前に現在の状態を確認します…",
        ["The rollback outcome cannot be proven. Automatic retry is not performed; manual recovery is required."] = "復旧結果を確認できません。自動で再実行は行いません。データを保管して配布担当者に相談してください。",
        ["The previous rollback outcome cannot be proven. Automatic retry is not performed; manual recovery is required."] = "以前の復旧結果を確認できません。自動で再実行は行いません。データを保管して配布担当者に相談してください。",
        ["Recovery evidence is incomplete. Automatic rollback is blocked; manual recovery is required."] = "復旧に必要な記録が不足しています。データを保管して配布担当者に相談してください。",
        ["Analyzing durable execution evidence. Rollback will not start automatically."] = "操作記録を調べています。復旧が自動で始まることはありません。",
        ["Recovery diagnosis was cancelled. Rollback remains blocked."] = "復旧の調査をキャンセルしました。復旧は開始できません。",
        ["Recovery diagnosis failed. Rollback remains blocked; technical details are not displayed."] = "復旧できるかを確認できませんでした。データを保管してください。",
        ["Recovery is required. Guarded rollback is available after explicit confirmation; it will not start automatically."] = "復旧が必要です。復旧内容を確認してから開始できます。自動では始まりません。",
        ["No rollback action is required. Automatic execution retry is not performed."] = "復旧で戻す操作はありません。移行が自動で再実行されることはありません。",
        ["Automatic rollback cannot be proven safe. Manual recovery is required; no automatic retry is performed."] = "安全に復旧できると確認できません。データを保管して配布担当者に相談してください。",
        ["Rollback is blocked because the required safety evidence could not be validated."] = "安全な復旧に必要な記録を検証できず、復旧を開始できません。",
        ["Recovered. Every planned rollback action has durable Applied evidence."] = "復旧が完了しました。すべての復旧操作の記録を確認しました。データの内容を確認してください。",
        ["GuardRejected. The current destination no longer matches the expected migration state and was not modified by rollback."] = "移行後に状態が変わっているため、復旧を拒否しました。復旧による変更はありません。",
        ["Rollback failed. Durable failure evidence was recorded; manual recovery is required."] = "復旧に失敗しました。記録とデータを保管して配布担当者に相談してください。",
        ["Rollback was cancelled before a safe completion could be established."] = "復旧の完了を確認する前にキャンセルしました。記録とデータを保管してください。",
        ["Rollback was blocked before a safe recovery could be completed."] = "安全に復旧できず停止しました。記録とデータを保管してください。",
        ["No migration result is available yet."] = "移行結果はまだありません。「移行する」画面から進めてください。",
        ["Report generated from existing read-only evidence. No workflow state was changed."] = "操作記録から結果を確認しました。結果の表示によるファイルの変更はありません。",
        ["Migration report is unavailable because evidence could not be validated."] = "記録を検証できず、移行結果を表示できません。成功として扱わず、データを保管してください。",
        ["Migration report generation failed. The migration result is unchanged; technical details are not displayed."] = "移行結果を表示できませんでした。成功として扱わず、データと操作記録を保管してください。",
        ["Choose source and destination, then select Generate Preview."] = "移行元と移行先を選び、「① 移行内容を調べる」を押してください。",
        ["Wait for the current operation. You can cancel; completion is never assumed."] = "処理中です。完了するまでお待ちください。キャンセルもできます。",
        ["Select conflict rows, choose Skip or Replace, then Apply choices."] = "既存項目のある行で、スキップか置換を決めてから「選択を確定」を押してください。",
        ["Apply choices to confirm your latest selection."] = "「選択を確定」で、変更した移行内容を確定してください。",
        ["Review the items and choose a separate safety workspace outside both instances."] = "移す項目を確認し、両インスタンスの外側にあるバックアップ・記録の保存先を選んでください。",
        ["Check capacity for the current selection and safety workspace."] = "「③ 空き容量を確認」を押してください。選択や保存先を変えた場合は確認し直します。",
        ["Select Execute migration to review the final confirmation."] = "「④ 移行を実行」で最終確認へ進みます。確認するまでファイルは変更しません。",
        ["Open Migration Report, verify the result, then check the new instance before launching Minecraft."] = "「⑤ 移行結果」で完了と内容確認の成功を確認し、新インスタンスのデータを確認してからMinecraftを起動してください。",
        ["Keep all folders and records. Review recovery before changing files or retrying."] = "再実行せず、すべてのフォルダーと記録を保管してください。復旧欄を確認してください。",
        ["Check the restored data. Keep the records; a new migration needs a fresh preview."] = "復旧後のデータを確認し、記録を保管してください。再移行する場合は最初から調べ直します。",
        ["Choose a workspace outside both instances, then check capacity again."] = "両インスタンスの外側にある別の保存先を選び、空き容量を確認し直してください。",
        ["Review the displayed reason and regenerate the preview after fixing it."] = "表示された理由を確認して問題を解消し、移行内容を調べ直してください。",
        ["Inspection failed"] = "調査に失敗しました",
        ["Dry-run preview failed"] = "移行内容の調査に失敗しました",
        ["Migration failed"] = "移行に失敗しました",
        ["Applying choices failed"] = "選択の確定に失敗しました",
        ["Migration completed."] = "移行が完了しました。",
        ["Verification succeeded."] = "コピー・置換した内容の確認に成功しました。",
        ["No files were changed."] = "ファイルは変更していません。",
        ["No result retained."] = "結果は保持していません。",
        ["Previous preview retained."] = "以前の移行内容を保持しています。",
        ["Review recovery evidence before retrying."] = "再実行せず、復旧情報を確認してください。",
        ["Review the safety workspace before retrying."] = "再実行せず、バックアップと操作記録を確認してください。",
        ["Migration is blocked before backup."] = "バックアップ前の確認で停止しました。",
        ["Migration is blocked."] = "移行を開始できません。",
        ["Migration could not continue."] = "移行を続けられませんでした。",
        ["Choices could not be applied."] = "選択を確定できませんでした。",
        ["Dry-run preview was not produced."] = "移行内容を調べられませんでした。",
        ["Dry-run preview inspection could not complete."] = "移行内容の調査を完了できませんでした。",
        ["Migration report is unavailable"] = "移行結果を確認できません",
        ["The migration result is unchanged."] = "結果の表示による変更はありません。",
        ["No row selected."] = "一覧の行を選んでください。",
        ["Known entries"] = "認識した項目",
        ["metadata observation complete"] = "調査の完了",
        ["Root state"] = "フォルダーの状態",
        ["Plan status"] = "移行内容の確認",
        ["Workflow state"] = "移行の状況",
        ["Copy"] = "コピー",
        ["Copied"] = "コピー済み",
        ["Replace"] = "置換",
        ["Replaced"] = "置換済み",
        ["Skip"] = "スキップ",
        ["Skipped"] = "スキップ済み",
        ["Selected"] = "対象",
        ["Included"] = "対象",
        ["Excluded"] = "対象外",
        ["No source"] = "移行元なし",
        ["source missing"] = "移行元なし",
        ["unresolved"] = "未決定",
        ["blocked"] = "移行不可",
        ["backup required"] = "バックアップが必要",
        ["Backup required"] = "バックアップが必要",
        ["Backup used"] = "バックアップを使用",
        ["conflict"] = "既存項目の扱い",
        ["Execution evidence"] = "操作記録",
        ["Applied"] = "実行済み",
        ["Failed"] = "失敗",
        ["Uncertain"] = "結果不明",
        ["rollback candidates"] = "復旧候補",
        ["Candidates"] = "復旧候補",
        ["candidates"] = "復旧候補",
        ["Delete created"] = "移行で作成した項目を削除",
        ["delete created"] = "移行で作成した項目を削除",
        ["Restore backup"] = "バックアップから戻す",
        ["restore backup"] = "バックアップから戻す",
        ["Planned writes"] = "予定の書き込み",
        ["Replace entries"] = "置換する項目",
        ["verification"] = "内容確認",
        ["Rules"] = "対象外のルール",
        ["Diagnosis"] = "復旧の調査",
        ["rollback"] = "復旧",
        ["Rollback outcome"] = "復旧の結果",
        ["Version"] = "バージョン",
        ["Author"] = "作成者",
        ["True"] = "はい",
        ["False"] = "いいえ",
        ["Unknown"] = "不明",
        ["Not applicable"] = "該当なし",
        ["Not generated"] = "未調査",
        ["Not inspected"] = "未調査",
        ["Not checked"] = "未確認",
        ["Not available"] = "確認できません",
        ["Not diagnosed"] = "未調査",
        ["Not started"] = "未実行",
        ["File"] = "ファイル",
        ["Directory"] = "フォルダー",
        ["Missing"] = "なし",
        ["Inaccessible"] = "アクセスできません",
        ["AccessDenied"] = "アクセスできません",
        ["Unavailable"] = "確認できません",
        ["ReparsePoint"] = "リンクのため対象外",
        ["UnknownKind"] = "種類不明",
        ["KindMismatch"] = "種類が一致しません",
        ["Ready"] = "準備完了",
        ["NeedsDecision"] = "既存項目の扱いを決めてください",
        ["Blocked"] = "開始できません",
        ["Completed"] = "完了",
        ["Succeeded"] = "成功",
        ["Cancelled"] = "キャンセル",
        ["RecoveryRequired"] = "復旧が必要",
        ["Recovered"] = "復旧完了",
        ["GuardRejected"] = "状態が変わったため拒否",
        ["NotRun"] = "未確認",
        ["NotRequired"] = "不要",
        ["NotStarted"] = "未実行",
        ["Invalid"] = "確認できません",
        ["Unresolved"] = "未決定",
        ["ReadyToCopy"] = "コピーできます",
        ["ReadyToReplace"] = "バックアップ後に置換できます",
        ["DestinationConflict"] = "移行先に既存項目があります",
        ["SkippedDestinationConflict"] = "既存項目を保持します",
        ["ExcludedBySelection"] = "選択で対象外",
        ["SourceMissing"] = "移行元にありません",
        ["SourceUnavailable"] = "移行元を確認できません",
        ["DestinationUnavailable"] = "移行先を確認できません",
        ["SourceKindMismatch"] = "移行元の種類が違います",
        ["DestinationKindMismatch"] = "移行先の種類が違います",
        ["SourceReparsePoint"] = "移行元がリンクです",
        ["DestinationReparsePoint"] = "移行先がリンクです",
        ["SelectRoots"] = "フォルダーを選択",
        ["ConfigurePlan"] = "移す項目を選択",
        ["Preview"] = "移行内容を確認",
        ["ReadyForBackup"] = "移行前の確認",
        ["BackupReady"] = "バックアップの準備完了",
        ["ReadyForExecution"] = "実行の準備完了",
        ["Executing"] = "移行中",
        ["WorkspaceUnsafe"] = "保存先を両インスタンスの外側にしてください",
        ["UnsafeWorkspace"] = "保存先を両インスタンスの外側にしてください",
        ["InsufficientDestinationSpace"] = "移行先の容量不足",
        ["InsufficientWorkspaceSpace"] = "バックアップ保存先の容量不足",
        ["InsufficientSharedVolumeSpace"] = "共有ドライブの容量不足",
        ["ManualRecoveryRequired"] = "手動の復旧が必要",
        ["RollbackAvailable"] = "確認後に復旧できます",
        ["InvalidState"] = "操作の順番を確認してください",
        ["InvalidRoots"] = "フォルダーの指定を確認してください",
        ["InspectionFailed"] = "フォルダーを調べられませんでした",
        ["PlanFailed"] = "移行内容を確認できませんでした",
        ["PlanNotReady"] = "移す項目と既存項目の扱いを確認してください",
        ["CapacityUnavailable"] = "空き容量を確認できません",
        ["CapacityInsufficient"] = "空き容量不足",
        ["BackupRequired"] = "バックアップ保存先が必要",
        ["JournalRequired"] = "操作記録の保存先が必要",
        ["BackupNotReady"] = "バックアップを開始できません",
        ["BackupFailed"] = "バックアップに失敗しました",
        ["ExecutionFailed"] = "移行に失敗しました",
        ["ExecutionRecoveryRequired"] = "移行結果を確認できず復旧が必要",
        ["MissingPreview"] = "移行内容の記録がありません",
        ["MissingExecutionEvidence"] = "実行記録がありません",
        ["InconsistentExecutionEvidence"] = "実行記録が一致しません",
        ["MissingRecoveryEvidence"] = "復旧記録がありません",
        ["InconsistentRecoveryEvidence"] = "復旧記録が一致しません",
        ["UnsupportedWorkflowState"] = "対応していない操作状態です",
    };

    // Index fixed phrases only. Rendered messages and paths are never cached.
    private static readonly IReadOnlyDictionary<char, KeyValuePair<string, string>[]> Phrases = Japanese
        .GroupBy(pair => pair.Key[0])
        .ToDictionary(group => group.Key, group => group.OrderByDescending(pair => pair.Key.Length).ToArray());

    public static string Translate(string text, bool japanese)
    {
        if (!japanese || string.IsNullOrEmpty(text))
        {
            return text;
        }
        if (Japanese.TryGetValue(text, out string? translated))
        {
            return translated;
        }
        if (text.Length > 8192)
        {
            return text;
        }
        var result = new StringBuilder(text.Length);
        for (int index = 0; index < text.Length;)
        {
            bool matched = false;
            if ((index == 0 || !IsWord(text[index - 1])) &&
                Phrases.TryGetValue(text[index], out KeyValuePair<string, string>[]? candidates))
            {
                foreach (var phrase in candidates)
                {
                    int end = index + phrase.Key.Length;
                    if (end <= text.Length && (end == text.Length || !IsWord(text[end])) &&
                        text.AsSpan(index).StartsWith(phrase.Key, StringComparison.Ordinal))
                    {
                        result.Append(phrase.Value);
                        index = end;
                        matched = true;
                        break;
                    }
                }
            }
            if (!matched)
            {
                result.Append(text[index++]);
            }
        }
        return result.ToString();
    }

    private static bool IsWord(char value) => char.IsLetterOrDigit(value) || value == '_';
}
